USE `ap`;
DROP PROCEDURE IF EXISTS `test`;

DELIMITER $$
USE `ap`$$
CREATE PROCEDURE `test`()
BEGIN
	DECLARE EXIT HANDLER FOR SQLWARNING
    BEGIN
		ROLLBACK;
	END;
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
		ROLLBACK;
	END;
    
    START TRANSACTION;
		UPDATE VENDORS SET VENDOR_NAME = 'FedUP' 
			WHERE VENDOR_ID = 123;
        UPDATE INVOICES SET VENDOR_ID = 123 
			WHERE VENDOR_ID = 122;
        DELETE FROM VENDORS 
			WHERE VENDOR_ID = 122;
	COMMIT;
END$$

DELIMITER ;
CALL test();